### ISSUE TITLE
Installation Diffculties - Unable to Access App Pages

### ISSUE THREAD

**Issue by LibraryIT** [folio-labs/folio-order-import-tool#48]
I am working on installing the order import tool and have run into a problem.   While the order import tool now passes all checks and the Jetty server starts just fine, I can't seem to actually access the app itself.  If I build a .WAR file and drop it in the server's root directory (/opt/jetty/my_base/webapp), I can only see a list of directories when I navigate to the app.  However if I call mvn jetty:run from within the container, I can't connect to the app at all.  I haven't tried building a Docker container because we don't use Docker here.  Being new to Java, it feels like I'm missing something.

**Comment by maccabeelevine** [comment]
It sounds like you're following the [directions](https://github.com/folio-labs/folio-order-import-tool#if-you-want-to-try-it) but just to confirm, you're accessing that app at /import right?  You should indeed just see a directory listing if you try the root path.  Beyond that I'm not sure I would check the Jetty logs to see any errors.  @nielserik may have other thoughts.

**Comment by LibraryIT** [comment]
For me /import throws a 404 error.  I can get the directory listing if I go /order, however.   Is there a chance we set the server up wrong?  Campus IT gave me the box and most of the directions I've found seem to indicate one can just drop a .war file in the /webapps directory, then restart Jetty.  But there must be more to it, because last summer I got the app working in a Docker container which may have been set up differently than our server.

**Comment by LibraryIT** [comment]
With a little help from Michelle Suranofsky, I was able to figure out the problem.  In order to get the app running outside of the /import context, one must change the servlet-mapping in the web.xml file to match where the app will live.  So for us, we now have:

```
  <servlet-mapping>
    <servlet-name>JerseyTest</servlet-name>
    <url-pattern>service/*</url-pattern>
  </servlet-mapping>
```

```
  <servlet-mapping>
     <servlet-name>OrderController</servlet-name>
     <url-pattern>/</url-pattern>
  </servlet-mapping>

```

I also adjusted the URL attributes in the upload-order.jsp file, but it does not seem to have made much of a difference.

**Comment by maccabeelevine** [comment]
@LibraryIT I'm glad to hear that helped.  @nielserik I would write up an addition to the README.md but not sure the specific use case for removing the context path, and not sure if we should go ahead until Michael's full install is working?

**Comment by LibraryIT** [comment]
I'm not sure it's necessary to wait for us to solve the remaining issue.  Currently we get either a 500 or 504 error when we attempt to import a record.  However the process does result in a new record in FOLIO so my current thinking is we need to open the university firewall a bit to allow FOLIO to communicate with the app.  I don't see how changing the context path would relate to this error.

**Comment by LibraryIT** [comment]
Ok I want to report that we solved the 5xx errors.  It seems the FOLIO user the app utilized did not have the correct permissions.  This morning I was able to import a record with no issues.

**Comment by maccabeelevine** [comment]
Great to hear, thanks!
